name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10.19
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.19
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        docker --username gcyagnam --password dckr_pat_F9sE_M0xf5Xdjf-g9LjZ_jfTDMk
        docker image build -t gcyagnam/gitops:hellov1.0 .
        docker push gcyagnam/gitops:hellov1.0
